# -*- coding: utf-8 -*-
"""Projeto01_calculadoira.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q_DAtl5yVG3dTrdc02NPQ47WeDwos8P7
"""

# calculadora:

print("CALCULADORA: \n")
print("Verifique se digitou o valor correspondente ao que o campo solicitou \n")

''' Armazenando os valores '''

numeros = []
operadores = []
op = "" # enquanto op for diferente de "=" o loop continua.

''' ARMAZENANDO VALORES '''

''' esse novo código trata as exceções e quando há para número ou operador
pede para entrar novamente com o valor correto de forma que, para cada número correto
na lista tenha um operador na outra lista também e vice-versa. '''

while op != "=":

# o loop executa infinitamente até que o break seja executado
# quando há exceção o 'continue' pede para que o loop reinicie
# se não houver exceção então a cláusula "else" é executada

  while True:

    try:
      numero = int(input("Entre com um numero: "))
      numeros.append(numero)
      print(numeros)
    except ValueError as e:
      print("Valores não compatíveis com o solicitado no campo: ", e, "\n")
      continue
    else:
      break

  while True:

    try:
      operador = input("Entre com um operador '+' '-' '*' '/' ou '=' para saber a resposta: ")

      if operador not in ['+', '-', '*', '/', '=']:
        raise ValueError("Valores válidos: '+' '-' '*' '/' ou '=' \n")

      operadores.append(operador)
      op = operador # ponteiro do loop externo
      print(operadores)

    except ValueError as e:
      print("Valores não compatíveis com o solicitado no campo: ", e, "\n")
      continue
    else:
      break



''' REALIZANDO O CALCULO '''

resultado = numeros[0]      # inicializo a variável com o primeiro número da lista 'numeros'
tamanho = len(operadores)   # método para obter quantidade de elementos na lista 'operadores'


while tamanho > 0:

    numeros.pop(0)          # para garantir while adicione sempre o próximo número

    for val in operadores:
        if val == "+":
          resultado += numeros[0]

        elif val == "-":
          resultado -= numeros[0]

        elif val == "*":
          resultado *= numeros[0]

        elif val == "/":
          resultado /= numeros[0]

        elif val == "=":
          print('...\n')
        break

    operadores.pop(0)       # para impedir que ele volte a iterar sobre o mesmo operador
    tamanho -= 1            # acompanha a quantidade atual de elementos na lista 'operadores'

print(f"O Valor obtido é: {resultado}")

